### ISSUE TITLE
Support for DS games.

### ISSUE THREAD

**Issue by GlowingUmbreon** [aspargas2/CartInstall#3]
It would be cool to have support for DS games, maybe even multiple options of what to do with them after, Put into roms/nds/ or gm9/out/ for example or make them appear on the home menu like a dsiware game.

**Comment by aspargas2** [comment]
As far as just copying them to a folder; that could be done just as well with a plain old GodMode9 script; the reason CartInstall is its own firm is to do things that can't currently be done in a script running in vanilla GodMode9. That said, I plan for all of CartInstall's functionality to make its way into vanilla GodMode9 eventually, at which point there would be no reason for CartInstall to even exist.

Making DS games automatically appear on the home menu automatically when dumping them is another matter entirely. As you may know, there's no way to convert cartridge DS games directly to CIAs like with DSiWare; the only way to have them on the home menu is to make CIAs which are just forwarders to nds-bootstrap (the backend that TWiLightmenu++ uses). The only program that I know of to generate these forwarder CIAs is a Java app called [Forwarder3-DS](https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/). Once I finish what I'm currently working on, which is getting a lot of CartInstall's code to the point where it's fit to be merged to GodMode9, I might look into the idea of writing a Forwarder3-DS equivalent to convert carts to forwarders directly, but I think it's definitely out of scope for CartInstall given that CartInstall isn't going to have any point in existing as soon as the next GodMode9 release happens.

**Comment by aspargas2** [comment]
With all that said, I'm going to close this now, but thanks for bringing that idea to my attention. I have no idea how practical it is, but I definitely will look into it eventually, because I agree it would be cool to have a 3ds-side app for the forwarder generation.

**Comment by GlowingUmbreon** [comment]
There is another way to have a nds file load from the home menu, i have no clue how it works tho 2bh.
