### ISSUE TITLE
Failed to Generate and Install Title Info Entry and Ticket

### ISSUE THREAD

**Issue by afrench97** [aspargas2/CartInstall#5]
Hi. 

I have been using your fork of gm9 to install carts on my N3dsXL and N3ds over the last couple of days. On my N3ds (with 64gb sd card), all of my games installed without issue. On my N3dsXL (with 256gb sd card) I got the following message with 3 of my games:

"Failed to Generate and Install Title Info Entry and Ticket. This should not happen; please report this as it is likely a bug. The SD title.db and CTRNAND ticket.db will now be restored to their original state." 

My first thought is that the issue is likely my 256gb sd card because I know there have been some issues with larger cards. 

Edit: The problem seems to have resolved after I switched back to a 32gb card.

**Comment by aspargas2** [comment]
@afrench97 While I'm pretty sure that this isn't an issue with CartInstall, the 256gb card should work fine unless it's somehow defective. Is it formatted to FAT32?

**Comment by afrench97** [comment]
It is formatted to fat32 with I believe 64k clusters. I think you’re right though. I don’t think it’s a problem with CartInstall. The same system with the same files (copied and pasted all of the files from 1 card to the other) worked fine on the smaller card I had. 
edit: I will try to reformat the larger card and copy the files back over to try again tomorrow.
